import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BatteryCharging, CalendarCheck, CheckCircle2, Gauge, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import { useAuth } from '../../../hooks/useAuth';
import { bookingService } from '../../../services/bookingService';
import type { Booking } from '../../../types';
import { UserRole } from '../../../constants/roles';
import { roleDashboard } from '../../../constants/routes';

export const Home = () => {
  const { isAuthenticated, user } = useAuth();
  const [reschedules, setReschedules] = useState<Booking[]>([]);
  useEffect(() => { if (isAuthenticated && user?.role === UserRole.MEMBER) void bookingService.getActive().then((items) => setReschedules(items.filter((item) => item.status === 'RESCHEDULE_PROPOSED'))); }, [isAuthenticated, user?.role]);
  const confirmReschedule = async (id: string) => { await bookingService.confirmReschedule(id); setReschedules((items) => items.filter((item) => item.id !== id)); };
  const primaryDestination = isAuthenticated ? roleDashboard(user?.role) : '/register';

  return <div className="space-y-20 pb-8 sm:space-y-28">
    {reschedules.map((booking) => <section key={booking.id} className="app-panel border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/30"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-extrabold text-amber-900 dark:text-amber-200">Trạm đề xuất đổi lịch</p><p className="mt-1 text-sm text-amber-800 dark:text-amber-300">{booking.rescheduleProposal?.reason} · {booking.rescheduleProposal?.scheduledStart ? new Date(booking.rescheduleProposal.scheduledStart).toLocaleString('vi-VN') : 'Chưa có thời gian mới'}</p></div><button onClick={() => void confirmReschedule(booking.id)} className="min-h-10 rounded-xl bg-amber-600 px-4 text-sm font-bold text-white">Xác nhận lịch mới</button></div></section>)}

    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-14 text-white sm:px-12 sm:py-20 lg:px-16 lg:py-24">
      <div className="soft-grid absolute inset-0 opacity-50" /><div className="absolute -right-32 -top-40 h-[520px] w-[520px] rounded-full bg-emerald-500/20 blur-3xl" /><div className="absolute -bottom-48 left-1/3 h-96 w-96 rounded-full bg-blue-500/10 blur-3xl" />
      <div className="relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider text-emerald-300"><Sparkles className="h-4 w-4" />An toàn pin, xuyên suốt hành trình</div><h1 className="mt-6 max-w-4xl text-4xl font-extrabold leading-[1.08] tracking-tight sm:text-6xl">Thay pin xe điện<br /><span className="text-emerald-400">đúng lúc, đúng chuẩn.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Theo dõi sức khỏe pin, đánh giá ngưỡng an toàn và hoàn tất quy trình thay pin minh bạch — từ đặt lịch đến lịch sử vòng đời.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={primaryDestination} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-500 px-6 text-sm font-extrabold text-slate-950 transition hover:bg-emerald-400">{isAuthenticated ? 'Mở bảng điều khiển' : 'Bắt đầu sử dụng'}<ArrowRight className="h-5 w-5" /></Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-slate-400"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Đánh giá theo dữ liệu thực</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Quy trình được kiểm soát</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Lịch sử truy xuất đầy đủ</span></div></div>
        <div className="relative mx-auto w-full max-w-md"><div className="absolute inset-0 rotate-3 rounded-[2rem] bg-emerald-500/20" /><div className="relative rounded-[2rem] border border-white/10 bg-white/[.07] p-6 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Đánh giá sức khỏe pin</p><p className="mt-1 text-lg font-extrabold">Từ dữ liệu đến hành động</p></div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-extrabold text-emerald-300">AN TOÀN</span></div><div className="my-8 grid place-items-center"><div className="relative grid h-44 w-44 place-items-center rounded-full border-[12px] border-white/10 before:absolute before:inset-[-12px] before:rotate-45 before:rounded-full before:border-[12px] before:border-transparent before:border-r-emerald-400 before:border-t-emerald-400"><BatteryCharging className="h-14 w-14 text-emerald-400" /><span className="absolute bottom-7 text-sm font-extrabold">Đang theo dõi</span></div></div><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-white/5 p-3"><Gauge className="mx-auto h-5 w-5 text-emerald-400" /><p className="mt-2 text-xs font-bold">Sức khỏe</p></div><div className="rounded-xl bg-white/5 p-3"><ShieldCheck className="mx-auto h-5 w-5 text-emerald-400" /><p className="mt-2 text-xs font-bold">An toàn</p></div><div className="rounded-xl bg-white/5 p-3"><CalendarCheck className="mx-auto h-5 w-5 text-emerald-400" /><p className="mt-2 text-xs font-bold">Dịch vụ</p></div></div></div></div>
      </div>
    </section>

    <section id="workflow"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">Một quy trình liền mạch</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Từ cảnh báo pin đến hoàn tất dịch vụ</h2><p className="mt-4 leading-7 text-slate-500 dark:text-slate-400">Mỗi bước đều có mục đích rõ ràng, người chịu trách nhiệm và lịch sử có thể truy xuất.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
      { icon: Gauge, step: '01', title: 'Theo dõi', text: 'Dữ liệu sức khỏe pin được đánh giá theo ngưỡng an toàn hiện hành.' },
      { icon: CalendarCheck, step: '02', title: 'Đặt lịch', text: 'Chọn trạm, thời gian và nhận mức phí được tính từ hệ thống.' },
      { icon: Wrench, step: '03', title: 'Thay pin', text: 'Nhân viên xác minh, tháo, kiểm tra và lắp pin tương thích.' },
      { icon: ShieldCheck, step: '04', title: 'Truy xuất', text: 'Thanh toán, vòng đời pin và lịch sử thay thế được lưu đầy đủ.' },
    ].map(({ icon: Icon, step, title, text }) => <article key={step} className="app-panel-hover relative overflow-hidden p-6"><span className="absolute right-5 top-3 text-5xl font-extrabold text-slate-100 dark:text-slate-800">{step}</span><span className="relative grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300"><Icon className="h-6 w-6" /></span><h3 className="relative mt-6 text-lg font-extrabold">{title}</h3><p className="relative mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p></article>)}</div></section>

    <section className="grid gap-8 rounded-[2rem] bg-emerald-50 p-6 sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center dark:bg-emerald-950/20"><div><p className="eyebrow">An toàn là ưu tiên</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight">Không chỉ là một lịch hẹn dịch vụ</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">BatterySwap biến dữ liệu pin thành hành động rõ ràng. Trạng thái an toàn cho phép tiếp tục sử dụng, cảnh báo đưa ra khuyến nghị, còn không an toàn tạo luồng thay pin ưu tiên bắt buộc.</p><Link to={primaryDestination} className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-emerald-700 dark:text-emerald-300">Khám phá hệ thống <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-3 sm:grid-cols-3">{[{ label: 'An toàn', detail: 'Tiếp tục theo dõi', color: 'emerald' }, { label: 'Cảnh báo', detail: 'Khuyến nghị đặt lịch', color: 'amber' }, { label: 'Không an toàn', detail: 'Thay pin ưu tiên', color: 'red' }].map((item) => <div key={item.label} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-extrabold ${item.color === 'emerald' ? 'bg-emerald-100 text-emerald-700' : item.color === 'amber' ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-700'}`}>{item.label}</span><p className="mt-4 text-sm font-bold">{item.detail}</p></div>)}</div></section>
  </div>;
};
