import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, Battery, Bell, CalendarClock, CarFront, CheckCircle2, Gauge, ShieldCheck } from 'lucide-react';
import { memberService, type MemberDashboardData } from '../../../services/memberService';
import { getApiErrorMessage } from '../../../services/apiClient';
import { SafetyBadge } from '../../../components/battery/SafetyBadge';

const safetyStyles = {
  SAFE: { panel: 'border-emerald-200 bg-emerald-50/60 dark:border-emerald-900 dark:bg-emerald-950/20', icon: 'bg-emerald-600', title: 'Pin đang ở trạng thái an toàn', text: 'Xe có thể tiếp tục vận hành và được theo dõi định kỳ.' },
  WARNING: { panel: 'border-amber-200 bg-amber-50/70 dark:border-amber-900 dark:bg-amber-950/20', icon: 'bg-amber-500', title: 'Pin cần được theo dõi', text: 'Nên chủ động đặt lịch kiểm tra hoặc thay pin trong thời gian sớm.' },
  UNSAFE: { panel: 'border-red-200 bg-red-50/70 dark:border-red-900 dark:bg-red-950/20', icon: 'bg-red-600', title: 'Yêu cầu thay pin bắt buộc', text: 'Pin đã vượt ngưỡng an toàn. Hãy đặt lịch ưu tiên theo hướng dẫn.' },
  UNKNOWN: { panel: 'border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900', icon: 'bg-slate-500', title: 'Chưa đủ dữ liệu đánh giá', text: 'Hệ thống chưa nhận được kết quả kiểm tra pin gần nhất.' },
} as const;

const DashboardSkeleton = () => <div className="space-y-6" aria-label="Đang tải bảng điều khiển"><div className="h-28 animate-pulse rounded-3xl bg-slate-200 dark:bg-slate-800" /><div className="grid gap-4 sm:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" />)}</div><div className="h-80 animate-pulse rounded-3xl bg-slate-200 dark:bg-slate-800" /></div>;

export const MemberDashboard = () => {
  const [data, setData] = useState<MemberDashboardData | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { memberService.dashboard().then(setData).catch((cause) => setError(getApiErrorMessage(cause))); }, []);
  const summary = useMemo(() => {
    const batteries = data?.vehicles.map((vehicle) => vehicle.batteryAssignments[0]?.battery).filter(Boolean) ?? [];
    return { vehicles: data?.vehicles.length ?? 0, alerts: batteries.filter((battery) => battery?.safetyState === 'WARNING' || battery?.safetyState === 'UNSAFE').length, notifications: data?.notifications.length ?? 0 };
  }, [data]);
  if (!data && !error) return <DashboardSkeleton />;
  if (error) return <div role="alert" className="app-panel border-red-200 p-6 dark:border-red-900"><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-red-50 text-red-600 dark:bg-red-950/50"><AlertTriangle className="h-5 w-5" /></span><div><h1 className="font-extrabold">Không thể tải bảng điều khiển</h1><p className="mt-1 text-sm text-slate-500">{error}</p><button onClick={() => window.location.reload()} className="mt-4 text-sm font-bold text-emerald-700">Thử lại</button></div></div></div>;

  const firstVehicle = data!.vehicles[0];
  const primaryBattery = firstVehicle?.batteryAssignments[0]?.battery;
  const primaryRequest = firstVehicle?.replacementRequests[0];
  const state = (primaryBattery?.safetyState ?? 'UNKNOWN') as keyof typeof safetyStyles;
  const safety = safetyStyles[state] ?? safetyStyles.UNKNOWN;
  const bookingLink = primaryRequest?.mandatory ? `/app/priority-replacement?requestId=${primaryRequest.id}` : '/app/bookings/new';

  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Không gian của bạn</p><h1 className="page-title mt-2">Xin chào, {data!.user.fullName}</h1><p className="page-description">Theo dõi an toàn pin và quản lý lịch thay pin cho xe điện của bạn.</p></div><Link to={bookingLink} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-extrabold text-white hover:bg-emerald-700"><CalendarClock className="h-5 w-5" />Đặt lịch thay pin</Link></div>

    {firstVehicle ? <section className={`relative overflow-hidden rounded-3xl border p-6 sm:p-8 ${safety.panel}`}>
      <div className="soft-grid absolute inset-0 opacity-40" /><div className="relative grid gap-7 lg:grid-cols-[1.4fr_.6fr] lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><span className={`grid h-12 w-12 place-items-center rounded-2xl text-white shadow-lg ${safety.icon}`}>{state === 'SAFE' ? <ShieldCheck className="h-6 w-6" /> : <AlertTriangle className="h-6 w-6" />}</span><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Trạng thái pin hiện tại</p><h2 className="mt-1 text-xl font-extrabold sm:text-2xl">{safety.title}</h2></div><SafetyBadge state={state} /></div><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{primaryRequest?.reason || safety.text}</p><div className="mt-6 flex flex-wrap gap-3"><Link to={`/app/battery-health/current?vehicleId=${firstVehicle.id}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white dark:bg-white dark:text-slate-950"><Gauge className="h-4 w-4" />Xem sức khỏe pin</Link>{state !== 'SAFE' && <Link to={bookingLink} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-slate-900 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:text-white dark:ring-slate-700">Xử lý ngay <ArrowRight className="h-4 w-4" /></Link>}</div></div>
      <div className="rounded-2xl border border-white/70 bg-white/75 p-5 backdrop-blur dark:border-slate-700 dark:bg-slate-900/70"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><CarFront className="h-5 w-5" /></span><div><p className="font-extrabold">{firstVehicle.name}</p><p className="text-xs text-slate-500">{firstVehicle.plateNumber}</p></div></div>{primaryBattery ? <div className="mt-5 grid grid-cols-2 gap-3"><div><p className="metric-label">SOH</p><p className="metric-value">{primaryBattery.soh}%</p></div><div><p className="metric-label">SOC</p><p className="metric-value">{primaryBattery.soc}%</p></div><div><p className="metric-label">Nhiệt độ</p><p className="mt-1 font-extrabold">{primaryBattery.temperature}°C</p></div><div><p className="metric-label">Chu kỳ</p><p className="mt-1 font-extrabold">{primaryBattery.cycleCount}</p></div></div> : <p className="mt-5 text-sm text-amber-700">Xe chưa có pin đang được gán.</p>}</div></div>
    </section> : <section className="app-panel p-8 text-center"><CarFront className="mx-auto h-10 w-10 text-slate-400" /><h2 className="mt-4 font-extrabold">Bạn chưa có xe nào</h2><p className="mt-2 text-sm text-slate-500">Liên hệ hỗ trợ để liên kết xe điện với tài khoản.</p></section>}

    <section className="grid gap-4 sm:grid-cols-3"><Link to="/app/vehicles" className="app-panel-hover p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300"><CarFront className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-slate-400" /></div><p className="metric-value">{summary.vehicles}</p><p className="metric-label mt-1">Xe đang quản lý</p></Link><Link to="/app/battery-health/current" className="app-panel-hover p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300"><AlertTriangle className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-slate-400" /></div><p className="metric-value">{summary.alerts}</p><p className="metric-label mt-1">Cảnh báo cần chú ý</p></Link><Link to="/app/notifications" className="app-panel-hover p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-950/50 dark:text-violet-300"><Bell className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-slate-400" /></div><p className="metric-value">{summary.notifications}</p><p className="metric-label mt-1">Thông báo gần đây</p></Link></section>

    <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="app-panel p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Phương tiện</p><h2 className="mt-2 text-lg font-extrabold">Tất cả xe của bạn</h2></div><Link to="/app/vehicles" className="text-sm font-bold text-emerald-700 dark:text-emerald-400">Xem tất cả</Link></div><div className="mt-5 space-y-3">{data!.vehicles.map((vehicle) => { const battery = vehicle.batteryAssignments[0]?.battery; return <Link key={vehicle.id} to={`/app/vehicles/${vehicle.id}`} className="flex items-center gap-4 rounded-2xl border p-4 transition hover:border-emerald-200 hover:bg-emerald-50/40 dark:hover:border-emerald-900 dark:hover:bg-emerald-950/20"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><CarFront className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="truncate font-extrabold">{vehicle.name}</p><p className="truncate text-xs text-slate-500">{vehicle.plateNumber} · {battery?.serialNumber ?? 'Chưa gán pin'}</p></div><SafetyBadge state={battery?.safetyState ?? 'UNKNOWN'} /><ArrowRight className="hidden h-4 w-4 text-slate-400 sm:block" /></Link>; })}</div></div>
      <div className="app-panel p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Cập nhật</p><h2 className="mt-2 text-lg font-extrabold">Thông báo gần đây</h2></div><Bell className="h-5 w-5 text-slate-400" /></div><div className="mt-5 space-y-1">{data!.notifications.length ? data!.notifications.slice(0, 5).map((item) => <div key={item.id} className="border-b py-3 last:border-0"><div className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500" /><div><p className="text-sm font-bold">{item.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{item.message}</p></div></div></div>) : <div className="py-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-500" /><p className="mt-3 text-sm font-bold">Không có thông báo mới</p></div>}</div><Link to="/app/notifications" className="mt-4 flex min-h-10 items-center justify-center gap-2 rounded-xl bg-slate-100 text-sm font-bold hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700">Xem trung tâm thông báo <ArrowRight className="h-4 w-4" /></Link></div>
    </section>

    <section className="app-panel grid gap-4 p-5 sm:grid-cols-2"><Link to="/app/bookings/new" className="flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50 dark:hover:bg-slate-800"><CalendarClock className="h-5 w-5 text-emerald-600" /><span className="text-sm font-bold">Đặt lịch thay pin</span></Link><Link to="/app/replacement-history" className="flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50 dark:hover:bg-slate-800"><Battery className="h-5 w-5 text-emerald-600" /><span className="text-sm font-bold">Xem lịch sử thay pin</span></Link></section>
  </div>;
};
