export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    GOOGLE: '/auth/google',
    REGISTER: '/auth/register',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
  },
  USERS: {
    ME: '/users/me',
    VEHICLES: '/users/me/vehicles',
    DASHBOARD: '/users/me/dashboard',
    VEHICLE: (id: string) => `/users/me/vehicles/${id}`,
  },
  ADMIN: {
    USERS: '/admin/users',
    USER_ROLE: (id: string) => `/admin/users/${id}/role`,
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    ROLES: '/admin/roles',
    PERMISSIONS: '/admin/permissions',
    SETTINGS: '/admin/settings',
    SETTING: (key: string) => `/admin/settings/${encodeURIComponent(key)}`,
  },
  STATIONS: {
    LIST: '/stations',
    DETAILS: (id: string) => `/stations/${id}`,
    SLOTS: (id: string) => `/stations/${id}/slots`,
      AVAILABILITY: (id: string) => `/stations/${id}/availability`,
      BOOKING_SCHEDULE: (id: string) => `/stations/${id}/booking-schedule`,
  },
  BOOKINGS: {
    LIST: '/bookings',
    CREATE: '/bookings',
    QUOTE: '/bookings/quote',
    ACTIVE: '/bookings/active',
    DETAILS: (id: string) => `/bookings/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    CONFIRM_RESCHEDULE: (id: string) => `/bookings/${id}/confirm-reschedule`,
  },
  SWAP: {
    CONTEXT: '/staff/context',
    STAFF_HISTORY: '/staff/history',
    HISTORY: '/swaps/history',
    LOOKUP: '/staff/bookings/lookup',
    CHECK_IN: (id: string) => `/staff/bookings/${id}/check-in`,
    DETAILS: (id: string) => `/staff/swaps/${id}`,
    VERIFY: (id: string) => `/staff/swaps/${id}/verify`,
    SCAN_BATTERY: (id: string) => `/staff/swaps/${id}/scan-battery`,
    REMOVE: (id: string) => `/staff/swaps/${id}/remove-battery`,
    INSPECT: (id: string) => `/staff/swaps/${id}/inspect-old-battery`,
    ASSIGN: (id: string) => `/staff/swaps/${id}/assign-replacement`,
    INSTALL: (id: string) => `/staff/swaps/${id}/install`,
    COLLECT_PAYMENT: (id: string) => `/staff/swaps/${id}/collect-payment`,
    ROLLBACK: (id: string) => `/staff/swaps/${id}/rollback`,
  },
  MANAGER_BOOKINGS: {
    PENDING: '/manager/bookings/pending',
    HISTORY: '/manager/bookings/history',
    DETAILS: (id: string) => `/manager/bookings/${id}`,
    APPROVE: (id: string) => `/manager/bookings/${id}/approve`,
    REJECT: (id: string) => `/manager/bookings/${id}/reject`,
    RESCHEDULE: (id: string) => `/manager/bookings/${id}/reschedule`,
  },
  PAYMENTS: {
    VNPAY_RETURN: '/payments/vnpay/return',
    BOOKING_STATUS: (id: string) => `/payments/bookings/${id}`,
    BOOKING_VNPAY: (id: string) => `/payments/bookings/${id}/vnpay`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_ALL_READ: '/notifications/read-all',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
  },
  REPORTS: {
    ANALYTICS: '/reports/analytics',
    INVENTORY: '/reports/inventory',
  },
};
