services:
  postgres:
    image: postgres:16-alpine
    container_name: battery-swap-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: SuperAdmin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: battery_swap_db

    ports:
      - "5432:5432"

    volumes:
      - battery_swap_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U SuperAdmin -d battery_swap_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  battery_swap_postgres_data: