import { expect, test, type Page } from '@playwright/test';
const login = async (page: Page, email: string, destination: RegExp) => { await page.goto('/login'); await page.getByLabel('Email').fill(email); await page.getByLabel('Mật khẩu').fill('123456'); await page.getByRole('button', { name: 'Đăng nhập' }).click(); await expect(page).toHaveURL(destination); };
const nextHour = () => { const date = new Date(); date.setHours(date.getHours() + 1, 0, 0, 0); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}T${String(date.getHours()).padStart(2, '0')}:00`; };

test('staff checks in and follows server-driven swap steps without manual swap id', async ({ browser }) => {
  test.setTimeout(120_000);
  const memberContext = await browser.newContext(); const managerContext = await browser.newContext(); const staffContext = await browser.newContext();
  const member = await memberContext.newPage(); const manager = await managerContext.newPage(); const staff = await staffContext.newPage();
  await login(member, 'member@batteryswap.local', /\/app\/dashboard$/); await login(manager, 'manager@batteryswap.local', /\/manager\/dashboard$/); await login(staff, 'staff@batteryswap.local', /\/staff\/dashboard$/);
  const vehicleHref = await member.getByRole('link', { name: / UNSAFE$/ }).first().getAttribute('href'); expect(vehicleHref).toBeTruthy(); await member.goto(`/app/bookings/new?vehicleId=${vehicleHref!.split('/').pop()}`); await member.getByLabel('Thời gian bắt đầu').fill(nextHour());
  await member.getByRole('button', { name: 'Kiểm tra slot và pin tương thích' }).click(); await expect(member.getByText('Đã tìm thấy pin SAFE tương thích')).toBeVisible(); const slot2 = await member.getByLabel('Slot khả dụng').locator('option', { hasText: 'Slot 2' }).getAttribute('value'); await member.getByLabel('Slot khả dụng').selectOption(slot2!); await member.getByRole('button', { name: 'Xem giá từ hệ thống' }).click(); await member.getByRole('button', { name: 'Xác nhận và giữ chỗ' }).click();
  try { await expect(member).toHaveURL(/\/app\/bookings\/[a-f0-9]{24}$/, { timeout: 10_000 }); } catch { await member.getByRole('button', { name: 'Xác nhận và giữ chỗ' }).click(); await expect(member).toHaveURL(/\/app\/bookings\/[a-f0-9]{24}$/, { timeout: 20_000 }); }
  const bookingId = member.url().split('/').pop()!; await manager.goto(`/manager/bookings/${bookingId}`); await manager.getByRole('button', { name: 'Xác nhận duyệt' }).click(); await expect(manager.getByText('APPROVED', { exact: true }).first()).toBeVisible();
  await staff.goto('/staff/check-in'); await staff.getByLabel('Mã booking').fill(bookingId); await staff.getByRole('button', { name: 'Tra cứu booking' }).click(); await expect(staff.getByText('APPROVED', { exact: true })).toBeVisible(); await staff.getByRole('button', { name: 'Check-in và bắt đầu' }).click(); await expect(staff).toHaveURL(/\/staff\/swaps\/[a-f0-9]{24}$/);
  await staff.getByRole('button', { name: 'Xác minh khách hàng, xe và pin' }).click(); await staff.getByLabel('Serial pin đang lắp').fill('WRONG-SERIAL'); await staff.getByLabel('SOC pin cũ').fill('18'); await staff.getByRole('button', { name: 'Xác nhận tháo pin cũ' }).click(); await expect(staff.getByRole('alert')).toContainText('Scanned battery is not installed');
  await staff.getByLabel('Serial pin đang lắp').fill('VF8-INSTALLED-UNSAFE-001'); await staff.getByRole('button', { name: 'Xác nhận tháo pin cũ' }).click(); await staff.getByLabel('SOH').fill('62'); await staff.getByLabel('Nhiệt độ').fill('58'); await staff.getByLabel('Điện áp').fill('310'); await staff.getByLabel('Tình trạng vật lý').fill('Vỏ pin nóng, cần cách ly kiểm tra'); await staff.getByLabel('Kết luận kiểm tra').selectOption('QUARANTINED'); await staff.getByLabel('Ghi chú').fill('Không được tái sử dụng trước khi kỹ thuật xác nhận'); await staff.getByRole('button', { name: 'Lưu biên bản kiểm tra' }).click();
  const replacementSerial = (await staff.locator('section').filter({ hasText: 'Pin SAFE đã giữ:' }).locator('strong').textContent())!.trim(); await staff.getByLabel('Quét serial pin thay thế').fill(replacementSerial); await staff.getByRole('button', { name: 'Gán đúng pin đã giữ' }).click(); await staff.getByLabel('Quét lại serial pin đã lắp').fill(replacementSerial); await staff.getByRole('button', { name: 'Xác nhận lắp pin' }).click();
  await staff.getByLabel('Lý do rollback').fill('E2E khôi phục xe và tài nguyên'); await staff.getByRole('button', { name: 'Rollback giao dịch' }).click(); await expect(staff.getByRole('button', { name: 'Rollback giao dịch' })).toHaveCount(0);
  await staff.goto('/staff/history'); await expect(staff.getByRole('heading', { name: 'Lịch sử thay pin tại trạm' })).toBeVisible();
  await memberContext.close(); await managerContext.close(); await staffContext.close();
});
