import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Button } from '../../../../components/ui/Button';
import { Input } from '../../../../components/ui/Input';
import { swapService, type InspectionInput, type StaffSwap } from '../../../../services/swapService';
import { getApiErrorMessage } from '../../../../services/apiClient';
import { LoadingSpinner } from '../../../../components/feedback/LoadingSpinner';
import { statusLabel } from '../../../../utils/viLabels';

const steps = ['NOT_STARTED', 'VERIFIED', 'OLD_BATTERY_REMOVED', 'OLD_BATTERY_INSPECTED', 'REPLACEMENT_ASSIGNED', 'INSTALLED', 'PAYMENT_PENDING', 'COMPLETED'];
export const ProcessSwap = () => {
  const { swapId = '' } = useParams(); const [swap, setSwap] = useState<StaffSwap | null>(null); const [serial, setSerial] = useState(''); const [soc, setSoc] = useState('');
  const [inspection, setInspection] = useState({ soh: '', temperature: '', voltage: '', physicalCondition: '', outcome: 'MAINTENANCE' as InspectionInput['outcome'], notes: '' }); const [rollbackReason, setRollbackReason] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = useCallback(() => swapService.get(swapId).then(setSwap).catch((cause) => setError(getApiErrorMessage(cause))), [swapId]); useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>) => { setLoading(true); setError(''); try { await action(); await load(); } catch (cause) { setError(getApiErrorMessage(cause)); } finally { setLoading(false); } };
  if (!swap && !error) return <LoadingSpinner label="Đang tải quy trình thay pin..." />; if (!swap) return <p role="alert" className="bg-red-50 p-4 text-red-700">{error}</p>;
  const status = swap.workflowStatus; const oldSerial = swap.booking?.vehicle ? swap.batteryIn?.serialNumber : undefined; const reservedSerial = swap.booking?.battery?.serialNumber ?? swap.batteryOut?.serialNumber;
  return <div className="space-y-6"><div><h1 className="text-3xl font-black">Quy trình thay pin</h1><p className="text-slate-500">Mã giao dịch {swap.id}; các thao tác được quyết định bởi trạng thái hệ thống.</p></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<ol className="grid gap-2 md:grid-cols-4">{steps.map((step, index) => <li key={step} className={`rounded-lg border p-3 text-xs font-bold ${index <= steps.indexOf(status) ? 'border-green-500 bg-green-50' : 'text-slate-400'}`}>{statusLabel(step)}</li>)}</ol><section className="rounded-2xl border bg-white p-6"><h2 className="font-black">Thông tin xác minh</h2><p>{swap.booking?.user.fullName} · {swap.booking?.vehicle?.name} · {swap.booking?.vehicle?.plateNumber}</p><p>Loại pin: <strong>{swap.booking?.vehicle?.batteryType || swap.vehicle?.batteryType || 'Không rõ'}</strong></p><p>Pin đặt trước: <strong>{reservedSerial ?? '-'}</strong></p>{swap.booking?.reason && <p>Ghi chú / Yêu cầu: <strong className="text-blue-700">{swap.booking.reason}</strong></p>}<p>Hành động tiếp theo: {swap.nextActions?.map(statusLabel).join(', ') || 'Không có'}</p></section>
    {status === 'NOT_STARTED' && <Button loading={loading} onClick={() => void run(() => swapService.verify(swap.id))}>Xác minh khách hàng, xe và pin</Button>}
    {status === 'VERIFIED' && <section className="rounded-2xl border bg-white p-5"><Input label="Mã pin đang lắp" value={serial} onChange={(e) => setSerial(e.target.value)} /><Input label="Mức pin cũ (SOC)" type="number" value={soc} onChange={(e) => setSoc(e.target.value)} /><Button className="mt-3" disabled={!serial || soc === ''} loading={loading} onClick={() => void run(() => swapService.remove(swap.id, serial, Number(soc)))}>Xác nhận tháo pin cũ</Button></section>}
    {status === 'OLD_BATTERY_REMOVED' && <section className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2"><Input label="Mã pin đã tháo" value={serial || oldSerial || ''} onChange={(e) => setSerial(e.target.value)} /><Input label="Mức pin (SOC)" type="number" value={soc} onChange={(e) => setSoc(e.target.value)} /><Input label="Sức khỏe pin (SOH)" type="number" value={inspection.soh} onChange={(e) => setInspection({ ...inspection, soh: e.target.value })} /><Input label="Nhiệt độ" type="number" value={inspection.temperature} onChange={(e) => setInspection({ ...inspection, temperature: e.target.value })} /><Input label="Điện áp" type="number" value={inspection.voltage} onChange={(e) => setInspection({ ...inspection, voltage: e.target.value })} /><Input label="Tình trạng vật lý" value={inspection.physicalCondition} onChange={(e) => setInspection({ ...inspection, physicalCondition: e.target.value })} /><label className="text-sm font-semibold">Kết luận<select aria-label="Kết luận kiểm tra" className="mt-1 w-full rounded-lg border p-3" value={inspection.outcome} onChange={(e) => setInspection({ ...inspection, outcome: e.target.value as InspectionInput['outcome'] })}>{['AVAILABLE','MAINTENANCE','QUARANTINED','RETIRED'].map((value) => <option key={value} value={value}>{statusLabel(value)}</option>)}</select></label><Input label="Ghi chú" value={inspection.notes} onChange={(e) => setInspection({ ...inspection, notes: e.target.value })} /><Button disabled={!serial || soc === '' || !inspection.soh || !inspection.physicalCondition} loading={loading} onClick={() => void run(() => swapService.inspect(swap.id, { serialNumber: serial, soc: Number(soc), soh: Number(inspection.soh), temperature: inspection.temperature ? Number(inspection.temperature) : undefined, voltage: inspection.voltage ? Number(inspection.voltage) : undefined, physicalCondition: inspection.physicalCondition, outcome: inspection.outcome, notes: inspection.notes || undefined }))}>Lưu biên bản kiểm tra</Button></section>}
    {status === 'OLD_BATTERY_INSPECTED' && <section className="rounded-2xl border bg-white p-5"><p>Pin an toàn đã giữ: <strong>{reservedSerial}</strong></p><Input label="Quét mã pin thay thế" value={serial} onChange={(e) => setSerial(e.target.value)} /><Button className="mt-3" disabled={!serial} loading={loading} onClick={() => void run(() => swapService.assign(swap.id, serial))}>Gán đúng pin đã giữ</Button></section>}
    {status === 'REPLACEMENT_ASSIGNED' && <section className="rounded-2xl border bg-white p-5"><Input label="Quét lại mã pin đã lắp" value={serial} onChange={(e) => setSerial(e.target.value)} /><Button className="mt-3" disabled={!serial} loading={loading} onClick={() => void run(() => swapService.install(swap.id, serial))}>Xác nhận lắp pin</Button></section>}
    {status === 'INSTALLED' && <section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="font-black">Yêu cầu thanh toán trực tiếp</h2><p className="mt-2 text-sm text-slate-500">Tạo hóa đơn theo giá lịch thay pin và gửi thông báo cho khách hàng. Khách hàng thanh toán trực tiếp qua VNPay, không sử dụng ví.</p><Button className="mt-4" loading={loading} onClick={() => void run(() => swapService.requestDirectPayment(swap.id))}>Gửi yêu cầu thanh toán VNPay</Button></section>}
    {status === 'PAYMENT_PENDING' && <p className="rounded-xl bg-amber-50 p-5 font-bold text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">Đang chờ khách hàng thanh toán trực tiếp qua VNPay. Hệ thống tự hoàn tất sau khi kết quả thanh toán được xác minh.</p>}
    {status === 'COMPLETED' && <p className="rounded-xl bg-green-50 p-5 font-bold text-green-700">Thay pin và thanh toán đã hoàn tất.</p>}
    {!['COMPLETED','ROLLED_BACK'].includes(status) && <section className="rounded-2xl border border-red-200 p-5"><Input label="Lý do hoàn tác" value={rollbackReason} onChange={(e) => setRollbackReason(e.target.value)} /><Button className="mt-3" variant="danger" disabled={rollbackReason.trim().length < 3} loading={loading} onClick={() => void run(() => swapService.rollback(swap.id, rollbackReason))}>Hoàn tác giao dịch</Button></section>}
  </div>;
};
export default ProcessSwap;
