import swaggerJSDoc from "swagger-jsdoc";
import { env } from "./env";

const operation = (summary: string, tag: string, protectedRoute = false) => ({
  summary,
  tags: [tag],
  ...(protectedRoute ? { security: [{ bearerAuth: [] }] } : {}),
  responses: {
    "200": { description: "Operation completed successfully" },
    "400": { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
    "401": { description: "Authentication required", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
    "403": { description: "Insufficient permission", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
    "404": { description: "Resource not found", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
    "409": { description: "Resource conflict", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
    "500": { description: "Internal server error", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
  },
});

export const swaggerSpec = swaggerJSDoc({
  definition: {
    openapi: "3.0.3",
    info: {
      title: "Battery Swapping System API",
      version: "1.0.0",
      description: "REST API for the Battery Swapping System backend.",
    },
    servers: [
      {
        url: `${env.SWAGGER_SERVER_URL}/api`,
        description: "Configured API server",
      },
    ],
    tags: ["Health", "Authentication", "Users", "Stations", "Batteries", "Battery health", "Battery slots", "Bay time slots", "Replacement requests", "Notifications", "Bookings", "Swaps", "Maintenance", "Payments", "Reports", "Admin", "Admin Vehicles"].map((name) => ({ name })),
    paths: {
      "/v1/health": { get: operation("Service health", "Health") },
      "/v1/health/database": { get: operation("Database health", "Health") },
      "/auth/login": { post: operation("Log in", "Authentication") },
      "/auth/register": { post: operation("Register", "Authentication") },
      "/auth/verify-email": { post: operation("Verify a registered email using a one-time link token", "Authentication") },
      "/auth/resend-verification": { post: operation("Resend an email verification link", "Authentication") },
      "/auth/refresh": { post: operation("Refresh access token", "Authentication") },
      "/auth/logout": { post: operation("Log out", "Authentication") },
      "/auth/profile": { get: operation("Get authenticated profile", "Authentication", true) },
      "/users/me": { get: operation("Get current user", "Users", true), patch: operation("Update current user", "Users", true) },
      "/users/me/vehicles": { get: operation("List my electric cars and installed battery packs", "Users", true) },
      "/users/me/dashboard": { get: operation("Get member vehicle, battery health, replacement and notification dashboard", "Users", true) },
      "/users/me/vehicles/{id}": { get: operation("Get owned electric-car detail and battery history", "Users", true) },
      "/stations": { get: operation("List stations", "Stations") },
      "/stations/{id}": { get: operation("Get station", "Stations") },
      "/stations/{id}/slots": { get: operation("List station slots", "Stations") },
      "/stations/{id}/available-bay-slots": { get: operation("List future available service-bay time slots", "Bay time slots") },
      "/stations/{id}/available-time-slots": { get: operation("List grouped service-bay time availability without exposing bay identities", "Bay time slots") },
      "/stations/{id}/availability": { get: operation("Find compatible battery and slot availability", "Stations", true) },
      "/batteries": { get: operation("List batteries", "Batteries") },
      "/batteries/faulty": { get: operation("List faulty batteries", "Batteries") },
      "/batteries/{id}": { get: operation("Get battery", "Batteries") },
      "/batteries/{id}/health": { get: operation("Get battery health history", "Battery health", true) },
      "/batteries/{id}/telemetry": { post: operation("Record and evaluate battery telemetry", "Battery health", true) },
      "/replacement-requests/me": { get: operation("List my replacement requests", "Replacement requests", true) },
      "/notifications": { get: operation("List my notifications", "Notifications", true) },
      "/notifications/read-all": { patch: operation("Mark all my notifications as read", "Notifications", true) },
      "/notifications/{id}/read": { patch: operation("Mark notification as read", "Notifications", true) },
      "/battery-slots": { get: operation("List battery slots", "Battery slots") },
      "/battery-slots/{id}": { get: operation("Get battery slot", "Battery slots") },
      "/bookings/active": { get: operation("Get active booking", "Bookings", true) },
      "/bookings": { post: operation("Create booking", "Bookings", true) },
      "/bookings/{id}": { get: operation("Get booking", "Bookings", true) },
      "/bookings/{id}/cancel": { post: operation("Cancel booking", "Bookings", true) },
      "/bookings/{id}/confirm-reschedule": { post: operation("Confirm manager reschedule proposal", "Bookings", true) },
      "/swaps/history": { get: operation("Get swap history", "Swaps", true) },
      "/manager/bookings/pending": { get: operation("List station bookings pending manager approval", "Bookings", true) },
      "/manager/bookings/{id}/approve": { post: operation("Approve booking", "Bookings", true) },
      "/manager/bookings/{id}/reject": { post: operation("Reject booking with reason", "Bookings", true) },
      "/manager/bookings/{id}/reschedule": { post: operation("Propose a new booking schedule", "Bookings", true) },
      "/staff/bookings/lookup": { post: operation("Look up a booking at assigned station", "Swaps", true) },
      "/staff/bookings/{id}/check-in": { post: operation("Check in approved booking and start swap", "Swaps", true) },
      "/staff/swaps/{id}": { get: operation("Get server-driven swap workflow", "Swaps", true) },
      "/staff/swaps/{id}/verify": { post: operation("Verify booking, vehicle and installed battery", "Swaps", true) },
      "/staff/swaps/{id}/remove-battery": { post: operation("Record old battery removal", "Swaps", true) },
      "/staff/swaps/{id}/inspect-old-battery": { post: operation("Record old battery inspection", "Swaps", true) },
      "/staff/swaps/{id}/assign-replacement": { post: operation("Assign reserved safe replacement battery", "Swaps", true) },
      "/staff/swaps/{id}/install": { post: operation("Confirm replacement battery installation", "Swaps", true) },
      "/staff/swaps/{id}/collect-payment": { post: operation("Collect payment and atomically complete swap", "Payments", true) },
      "/staff/swaps/{id}/rollback": { post: operation("Compensate and roll back failed swap", "Swaps", true) },
      "/maintenance": { get: operation("List maintenance records", "Maintenance", true), post: operation("Create maintenance record", "Maintenance", true) },
      "/payments/wallet": { get: operation("Get wallet", "Payments", true) },
      "/payments/vnpay/create-payment": { post: operation("Create VNPay payment", "Payments", true) },
      "/payments/vnpay/ipn": { get: operation("Receive VNPay IPN", "Payments") },
      "/payments/vnpay/return": { get: operation("Handle VNPay return", "Payments") },
      "/reports/analytics": { get: operation("Get analytics", "Reports", true) },
      "/reports/inventory": { get: operation("Get inventory report", "Reports", true) },
      "/admin/overview": { get: operation("Get admin overview", "Admin", true) },
      "/admin/stations/{stationId}/bay-slots": { get: operation("List bay time slots by Vietnam date", "Bay time slots", true) },
      "/admin/stations/{stationId}/bay-slots/bulk": { post: operation("Create bay time slots in bulk", "Bay time slots", true) },
      "/admin/bays/{bayId}/slots": { post: operation("Create one bay time slot", "Bay time slots", true) },
      "/admin/bay-slots/{slotId}/status": { patch: operation("Turn off, enable, block, or unblock a bay time slot", "Bay time slots", true) },
      "/admin/bay-slots/{slotId}": { delete: operation("Delete an empty future bay time slot", "Bay time slots", true) },
      "/admin/bay-slots/bulk-status": { patch: operation("Apply a status action to multiple bay time slots", "Bay time slots", true) },
      "/admin/audit-logs": { get: operation("List audit logs", "Admin", true) },
      "/admin/settings": { get: operation("List system settings", "Admin", true) },
      "/admin/settings/{key}": { put: operation("Persist system setting with audit", "Admin", true) },
      "/admin/users": { get: operation("List users", "Admin", true) },
      "/admin/roles": { get: operation("List roles", "Admin", true) },
      "/admin/permissions": { get: operation("List permissions", "Admin", true) },
      "/admin/users/{id}/role": { patch: operation("Update user role", "Admin", true) },
      "/admin/users/{id}/status": { patch: operation("Update user status", "Admin", true) },
      "/admin/vehicles": { get: operation("Danh sách, bộ lọc và thống kê xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}": { get: operation("Chi tiết xe dành cho quản trị viên", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/battery-health": { get: operation("Sức khỏe pin hiện tại", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/battery-health-logs": { get: operation("Nhật ký sức khỏe pin", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/swap-history": { get: operation("Lịch sử đổi pin của xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/maintenance-history": { get: operation("Lịch sử bảo trì xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/incidents": { get: operation("Danh sách sự cố xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/ownership-history": { get: operation("Lịch sử quyền sở hữu bất biến", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/transfer-requests": { get: operation("Yêu cầu chuyển quyền của xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/audit-logs": { get: operation("Nhật ký quản trị bất biến của xe", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/lock": { patch: operation("Khóa xe có lý do và ghi audit", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/unlock": { patch: operation("Mở khóa và khôi phục trạng thái an toàn", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/mark-needs-inspection": { patch: operation("Đánh dấu xe cần kiểm tra", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/mark-maintenance": { patch: operation("Chuyển xe sang bảo trì", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/deactivate": { patch: operation("Ngừng hoạt động xe, không xóa lịch sử", "Admin Vehicles", true) },
      "/admin/vehicles/{vehicleId}/identifier-correction-requests": { post: operation("Tạo yêu cầu sửa VIN có kiểm soát", "Admin Vehicles", true) },
      "/admin/swap-transactions": { get: operation("Danh sách và lọc giao dịch đổi pin toàn hệ thống", "Admin", true) },
      "/admin/swap-transactions/{transactionId}": { get: operation("Chi tiết vận hành, kỹ thuật và thanh toán an toàn của giao dịch đổi pin", "Admin", true) },
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        Error: {
          type: "object",
          required: ["success", "code", "message", "errors"],
          properties: {
            success: { type: "boolean", example: false },
            code: { type: "string", example: "VALIDATION_ERROR" },
            message: { type: "string", example: "Invalid request data" },
            errors: { type: "array", items: { type: "object" } },
            requestId: { type: "string", format: "uuid" },
          },
        },
        ObjectId: { type: "string", pattern: "^[a-fA-F0-9]{24}$", example: "507f1f77bcf86cd799439011" },
        BatterySafetyState: { type: "string", enum: ["UNKNOWN", "SAFE", "WARNING", "UNSAFE"] },
        BatteryOperationalStatus: { type: "string", enum: ["AVAILABLE", "RESERVED", "INSTALLED", "REMOVED", "INSPECTION_REQUIRED", "MAINTENANCE", "QUARANTINED", "RETIRED"] },
        BookingStatus: { type: "string", enum: ["CREATED", "PENDING_APPROVAL", "APPROVED", "REJECTED", "RESCHEDULE_PROPOSED", "RESCHEDULED", "CHECKED_IN", "COMPLETED", "CANCELLED", "EXPIRED"] },
        SwapStatus: { type: "string", enum: ["NOT_STARTED", "VERIFIED", "OLD_BATTERY_REMOVED", "OLD_BATTERY_INSPECTED", "REPLACEMENT_ASSIGNED", "INSTALLED", "PAYMENT_PENDING", "COMPLETED", "FAILED", "ROLLED_BACK"] },
        PaymentStatus: { type: "string", enum: ["PENDING", "PROCESSING", "SUCCESS", "FAILED", "CANCELLED", "REFUNDED"] },
      },
      parameters: {
        Page: { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } },
        Limit: { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } },
      },
    },
  },
  apis: ["src/modules/**/*.route.ts", "src/modules/**/*.controller.ts"],
});
