import { Router } from "express";
import { authorizePermission } from "../../common/middleware/authorize-permission.middleware";
import { validate } from "../../common/middleware/validate.middleware";
import { Permissions } from "../../constants/permissions";
import { stationDetailController as c } from "./station-detail.controller";
import * as v from "./station-detail.validation";

export const stationDetailRouter = Router({ mergeParams: true });
stationDetailRouter.use(authorizePermission(Permissions.SETTINGS_MANAGE));
stationDetailRouter.get("/", validate({ params: v.stationParamSchema }), c.detail);
stationDetailRouter.get("/overview", validate({ params: v.stationParamSchema }), c.overview);
stationDetailRouter.get("/bays", validate({ params: v.stationParamSchema }), c.bays);
stationDetailRouter.post("/bays", validate({ params: v.stationParamSchema, body: v.createBaySchema }), c.createBay);
stationDetailRouter.patch("/bays/:bayId", validate({ params: v.bayParamSchema, body: v.updateBaySchema }), c.updateBay);
stationDetailRouter.delete("/bays/:bayId", validate({ params: v.bayParamSchema }), c.deleteBay);
stationDetailRouter.get("/slots", validate({ params: v.stationParamSchema, query: v.slotsQuerySchema }), c.slots);
stationDetailRouter.post("/slots", validate({ params: v.stationParamSchema, body: v.createSlotSchema }), c.createSlot);
stationDetailRouter.patch("/slots/:slotId", validate({ params: v.slotParamSchema, body: v.updateSlotSchema }), c.updateSlot);
stationDetailRouter.delete("/slots/:slotId", validate({ params: v.slotParamSchema }), c.deleteSlot);
stationDetailRouter.get("/inventory", validate({ params: v.stationParamSchema, query: v.inventoryQuerySchema }), c.inventory);
stationDetailRouter.patch("/inventory/:batteryId", validate({ params: v.batteryParamSchema, body: v.inventoryActionSchema }), c.updateInventory);
stationDetailRouter.get("/inventory/:batteryId/history", validate({ params: v.batteryParamSchema }), c.inventoryHistory);
stationDetailRouter.get("/bookings", validate({ params: v.stationParamSchema, query: v.bookingsQuerySchema }), c.bookings);
stationDetailRouter.get("/assignment-candidates", validate({ params: v.stationParamSchema }), c.assignmentCandidates);
stationDetailRouter.get("/assignments", validate({ params: v.stationParamSchema }), c.assignments);
stationDetailRouter.post("/assignments", validate({ params: v.stationParamSchema, body: v.createAssignmentSchema }), c.createAssignment);
stationDetailRouter.patch("/assignments/:assignmentId", validate({ params: v.assignmentParamSchema, body: v.updateAssignmentSchema }), c.updateAssignment);
stationDetailRouter.delete("/assignments/:assignmentId", validate({ params: v.assignmentParamSchema }), c.deleteAssignment);
stationDetailRouter.get("/maintenance", validate({ params: v.stationParamSchema, query: v.maintenanceQuerySchema }), c.maintenance);
stationDetailRouter.post("/maintenance", validate({ params: v.stationParamSchema, body: v.createMaintenanceSchema }), c.createMaintenance);
stationDetailRouter.patch("/maintenance/:maintenanceId", validate({ params: v.maintenanceParamSchema, body: v.updateMaintenanceSchema }), c.updateMaintenance);
stationDetailRouter.get("/reports", validate({ params: v.stationParamSchema, query: v.reportQuerySchema }), c.reports);
stationDetailRouter.get("/audit-logs", validate({ params: v.stationParamSchema, query: v.auditQuerySchema }), c.auditLogs);
