import { prisma } from "../../config/database";
import { BadRequestError } from "../../common/errors/bad-request-error";
import { ConflictError } from "../../common/errors/conflict-error";
import { NotFoundError } from "../../common/errors/not-found-error";

const ensureStation = async (stationId: string) => {
  const station = await prisma.station.findUnique({ where: { id: stationId } });
  if (!station) throw new NotFoundError("Station not found");
  return station;
};
const audit = (adminId: string, stationId: string, action: string, entityType: string, entityId: string, before?: unknown, after?: unknown) => prisma.auditLog.create({ data: { adminId, stationId, actorRole: "ADMIN", action, entityType, entityId, before: before as never, after: after as never } });
const dayBounds = (date = new Date()) => { const start = new Date(date); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { start, end }; };

export const stationDetailService = {
  detail: async (stationId: string) => ensureStation(stationId),
  overview: async (stationId: string) => {
    const station = await ensureStation(stationId); const { start, end } = dayBounds();
    const [bays, slots, bookings, batteries, assignments, recentBookings, recentIncidents] = await Promise.all([
      prisma.serviceBay.groupBy({ by: ["status"], where: { stationId }, _count: true }),
      prisma.replacementSlot.groupBy({ by: ["status"], where: { stationId, date: { gte: start, lt: end } }, _count: true }),
      prisma.booking.count({ where: { stationId, scheduledStart: { gte: start, lt: end } } }),
      prisma.battery.groupBy({ by: ["operationalStatus"], where: { stationId }, _count: true }),
      prisma.stationAssignment.findMany({ where: { stationId, active: true }, include: { user: { select: { id: true, fullName: true, email: true } } } }),
      prisma.booking.findMany({ where: { stationId }, include: { user: { select: { fullName: true } }, vehicle: { select: { name: true, plateNumber: true } } }, orderBy: { createdAt: "desc" }, take: 5 }),
      prisma.stationMaintenanceEvent.findMany({ where: { stationId, type: "INCIDENT" }, orderBy: { createdAt: "desc" }, take: 5 }),
    ]);
    const bayCounts = Object.fromEntries(bays.map((x) => [x.status, x._count])); const slotCounts = Object.fromEntries(slots.map((x) => [x.status, x._count])); const batteryCounts = Object.fromEntries(batteries.map((x) => [x.operationalStatus, x._count]));
    return { station, totalBays: Object.values(bayCounts).reduce((a, b) => a + b, 0), availableBays: bayCounts.AVAILABLE ?? 0, maintenanceBays: bayCounts.MAINTENANCE ?? 0, totalSlotsToday: Object.values(slotCounts).reduce((a, b) => a + b, 0), availableSlotsToday: slotCounts.AVAILABLE ?? 0, fullSlotsToday: slotCounts.FULL ?? 0, todayBookings: bookings, availableBatteries: batteryCounts.AVAILABLE ?? 0, reservedBatteries: batteryCounts.RESERVED ?? 0, inspectionBatteries: batteryCounts.INSPECTION_REQUIRED ?? 0, maintenanceBatteries: batteryCounts.MAINTENANCE ?? 0, manager: assignments.find((x) => x.assignmentRole === "MANAGER")?.user ?? null, assignedStaffCount: assignments.filter((x) => x.assignmentRole !== "MANAGER").length, recentBookings, recentIncidents, lowInventoryAlerts: (batteryCounts.AVAILABLE ?? 0) < Math.max(1, Object.values(bayCounts).reduce((a, b) => a + b, 0)) ? 1 : 0 };
  },
  listBays: async (stationId: string) => { await ensureStation(stationId); return prisma.serviceBay.findMany({ where: { stationId }, orderBy: { bayCode: "asc" } }); },
  createBay: async (stationId: string, input: any, adminId: string) => { await ensureStation(stationId); const exists = await prisma.serviceBay.findFirst({ where: { stationId, bayCode: input.bayCode } }); if (exists) throw new ConflictError("Bay code already exists at this station"); const item = await prisma.serviceBay.create({ data: { ...input, stationId } }); await audit(adminId, stationId, "CREATE_SERVICE_BAY", "ServiceBay", item.id, undefined, item); return item; },
  updateBay: async (stationId: string, bayId: string, input: any, adminId: string) => { await ensureStation(stationId); const before = await prisma.serviceBay.findFirst({ where: { id: bayId, stationId } }); if (!before) throw new NotFoundError("Service bay not found"); const item = await prisma.serviceBay.update({ where: { id: bayId }, data: input }); await audit(adminId, stationId, "UPDATE_SERVICE_BAY", "ServiceBay", bayId, before, item); return item; },
  deleteBay: async (stationId: string, bayId: string, adminId: string) => { await ensureStation(stationId); const before = await prisma.serviceBay.findFirst({ where: { id: bayId, stationId } }); if (!before) throw new NotFoundError("Service bay not found"); if (await prisma.replacementSlot.count({ where: { bayId } })) throw new ConflictError("Cannot delete a bay that has replacement slots"); await prisma.serviceBay.delete({ where: { id: bayId } }); await audit(adminId, stationId, "DELETE_SERVICE_BAY", "ServiceBay", bayId, before); return { success: true }; },
  listSlots: async (stationId: string, query: any) => { await ensureStation(stationId); const { start, end } = query.from ? { start: query.from, end: query.to ?? new Date(query.from.getTime() + (query.view === "week" ? 7 : 1) * 86400000) } : dayBounds(); return prisma.replacementSlot.findMany({ where: { stationId, date: { gte: start, lt: end } }, orderBy: [{ date: "asc" }, { startTime: "asc" }] }); },
  createSlot: async (stationId: string, input: any, adminId: string) => { const station = await ensureStation(stationId); const bay = await prisma.serviceBay.findFirst({ where: { id: input.bayId, stationId } }); if (!bay) throw new NotFoundError("Service bay not found"); if (station.openingTime && input.startTime < station.openingTime || station.closingTime && input.endTime > station.closingTime) throw new BadRequestError("Slot must be inside station operating hours"); const { start, end } = dayBounds(input.date); const overlap = await prisma.replacementSlot.findFirst({ where: { bayId: input.bayId, date: { gte: start, lt: end }, startTime: { lt: input.endTime }, endTime: { gt: input.startTime }, status: { notIn: ["CANCELLED"] } } }); if (overlap) throw new ConflictError("This bay already has an overlapping slot"); const item = await prisma.replacementSlot.create({ data: { ...input, stationId } }); await audit(adminId, stationId, "CREATE_REPLACEMENT_SLOT", "ReplacementSlot", item.id, undefined, item); return item; },
  updateSlot: async (stationId: string, slotId: string, input: any, adminId: string) => { const station = await ensureStation(stationId); const before = await prisma.replacementSlot.findFirst({ where: { id: slotId, stationId } }); if (!before) throw new NotFoundError("Replacement slot not found"); if ((before.bookedCount > 0 || before.reservedCount > 0) && (input.date || input.startTime || input.endTime || input.bayId)) throw new ConflictError("Slots with active bookings require rescheduling"); const next = { ...before, ...input }; if (next.startTime >= next.endTime) throw new BadRequestError("Start time must be earlier than end time"); if (station.openingTime && next.startTime < station.openingTime || station.closingTime && next.endTime > station.closingTime) throw new BadRequestError("Slot must be inside station operating hours"); const { start, end } = dayBounds(next.date); const overlap = await prisma.replacementSlot.findFirst({ where: { id: { not: slotId }, bayId: next.bayId, date: { gte: start, lt: end }, startTime: { lt: next.endTime }, endTime: { gt: next.startTime }, status: { notIn: ["CANCELLED"] } } }); if (overlap) throw new ConflictError("This bay already has an overlapping slot"); const item = await prisma.replacementSlot.update({ where: { id: slotId }, data: input }); await audit(adminId, stationId, "UPDATE_REPLACEMENT_SLOT", "ReplacementSlot", slotId, before, item); return item; },
  deleteSlot: async (stationId: string, slotId: string, adminId: string) => { await ensureStation(stationId); const before = await prisma.replacementSlot.findFirst({ where: { id: slotId, stationId } }); if (!before) throw new NotFoundError("Replacement slot not found"); if (before.bookedCount > 0 || before.reservedCount > 0) throw new ConflictError("Cannot delete a slot containing active bookings"); await prisma.replacementSlot.delete({ where: { id: slotId } }); await audit(adminId, stationId, "DELETE_REPLACEMENT_SLOT", "ReplacementSlot", slotId, before); return { success: true }; },
  inventory: async (stationId: string, query: any) => { await ensureStation(stationId); const where: any = { stationId }; if (query.status) where.operationalStatus = query.status; if (query.safetyState) where.safetyState = query.safetyState; if (query.search) where.OR = [{ batteryCode: { contains: query.search, mode: "insensitive" } }, { serialNumber: { contains: query.search, mode: "insensitive" } }]; const [items, total] = await Promise.all([prisma.battery.findMany({ where, include: { batteryType: { include: { compatibilities: { where: { active: true }, include: { vehicleModel: true } } } }, reservations: { where: { status: "ACTIVE" }, take: 1 }, inspections: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.battery.count({ where })]); return { items, total, page: query.page, limit: query.limit }; },
  updateInventory: async (stationId: string, batteryId: string, input: any, adminId: string) => {
    await ensureStation(stationId);
    const isObjectId = /^[0-9a-fA-F]{24}$/.test(batteryId);
    let battery = await prisma.battery.findFirst({
      where: {
        OR: [
          ...(isObjectId ? [{ id: batteryId }] : []),
          { batteryCode: batteryId },
          { serialNumber: batteryId },
        ],
      },
    });

    if (!battery && input.action === "ADD") {
      const batteryType = await prisma.batteryType.findFirst();
      if (!batteryType) throw new BadRequestError("No battery type found in system");
      battery = await prisma.battery.create({
        data: {
          batteryCode: batteryId,
          serialNumber: batteryId,
          batteryTypeId: batteryType.id,
          stationId,
          soc: 100,
          soh: 100,
          temperature: 25.0,
          voltage: 400.0,
          safetyState: "SAFE",
          operationalStatus: "AVAILABLE",
        },
      });
    }

    if (!battery) throw new NotFoundError("Battery not found");
    if (input.action !== "ADD" && battery.stationId !== stationId) throw new NotFoundError("Battery is not stored at this station");
    if (input.action === "ADD" && battery.stationId && battery.stationId !== stationId) throw new ConflictError("Battery already belongs to another station; use transfer");
    if (input.action === "TRANSFER" && ["RESERVED", "INSTALLED"].includes(battery.operationalStatus)) throw new ConflictError("Reserved or installed batteries cannot be transferred");
    if (input.targetStationId) await ensureStation(input.targetStationId);

    const targetBatteryId = battery.id;
    const nextStationId = input.action === "TRANSFER" ? input.targetStationId : stationId;
    const nextStatus = input.action === "INSPECTION_REQUIRED" ? "INSPECTION_REQUIRED" : input.action === "MAINTENANCE" ? "MAINTENANCE" : battery.operationalStatus;
    const item = await prisma.$transaction(async (tx) => {
      const updated = await tx.battery.update({ where: { id: targetBatteryId }, data: { stationId: nextStationId, operationalStatus: nextStatus } });
      await tx.batteryLifecycleEvent.create({ data: { batteryId: targetBatteryId, actorId: adminId, eventType: `STATION_INVENTORY_${input.action}`, fromStatus: battery.operationalStatus, toStatus: nextStatus, safetyState: battery.safetyState, reason: input.reason, snapshot: { fromStationId: battery.stationId, toStationId: nextStationId } } });
      return updated;
    });
    await audit(adminId, stationId, `STATION_INVENTORY_${input.action}`, "Battery", targetBatteryId, battery, item);
    return item;
  },
  inventoryHistory: async (stationId: string, batteryId: string) => { await ensureStation(stationId); const battery = await prisma.battery.findFirst({ where: { id: batteryId, stationId } }); if (!battery) throw new NotFoundError("Battery is not stored at this station"); return prisma.batteryLifecycleEvent.findMany({ where: { batteryId }, include: { actor: { select: { id: true, fullName: true, email: true } } }, orderBy: { createdAt: "desc" } }); },
  bookings: async (stationId: string, query: any) => { await ensureStation(stationId); const where: any = { stationId }; if (query.status) where.status = query.status; if (query.from || query.to) where.scheduledStart = { ...(query.from ? { gte: query.from } : {}), ...(query.to ? { lte: query.to } : {}) }; if (query.search) { where.OR = [{ user: { fullName: { contains: query.search, mode: "insensitive" } } }, { vehicle: { plateNumber: { contains: query.search, mode: "insensitive" } } }]; if (/^[0-9a-fA-F]{24}$/.test(query.search)) { where.OR.push({ id: query.search }); } } const [items, total] = await Promise.all([prisma.booking.findMany({ where, include: { user: { select: { id: true, fullName: true, email: true } }, vehicle: true, battery: true, serviceBay: true, slot: true, approvalHistory: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.booking.count({ where })]); return { items, total, page: query.page, limit: query.limit }; },
  assignments: async (stationId: string) => { await ensureStation(stationId); return prisma.stationAssignment.findMany({ where: { stationId }, include: { user: { select: { id: true, fullName: true, email: true, phone: true, role: { select: { name: true } } } } }, orderBy: { createdAt: "desc" } }); },
  assignmentCandidates: async (stationId: string) => { await ensureStation(stationId); return prisma.user.findMany({ where: { status: "ACTIVE", role: { name: { in: ["MANAGER", "STAFF", "TECHNICIAN"] } } }, select: { id: true, fullName: true, email: true, role: { select: { name: true } } }, orderBy: { fullName: "asc" } }); },
  createAssignment: async (stationId: string, input: any, adminId: string) => { await ensureStation(stationId); const user = await prisma.user.findUnique({ where: { id: input.userId }, include: { role: true } }); if (!user) throw new NotFoundError("User not found"); if (user.role.name !== input.assignmentRole) throw new BadRequestError(`User role must be ${input.assignmentRole}`); if (input.shift) { const conflict = await prisma.stationAssignment.findFirst({ where: { userId: input.userId, shift: input.shift, active: true, stationId: { not: stationId } } }); if (conflict) throw new ConflictError("User already has an active assignment in this shift at another station"); } const existing = await prisma.stationAssignment.findFirst({ where: { stationId, userId: input.userId, assignmentRole: input.assignmentRole } }); const item = existing ? await prisma.stationAssignment.update({ where: { id: existing.id }, data: { ...input, active: true, effectiveFrom: input.effectiveFrom ?? new Date(), effectiveTo: input.effectiveTo ?? null } }) : await prisma.stationAssignment.create({ data: { ...input, stationId, active: true, effectiveFrom: input.effectiveFrom ?? new Date() } }); await audit(adminId, stationId, "ASSIGN_STATION_STAFF", "StationAssignment", item.id, existing, item); return item; },
  updateAssignment: async (stationId: string, assignmentId: string, input: any, adminId: string) => { await ensureStation(stationId); const before = await prisma.stationAssignment.findFirst({ where: { id: assignmentId, stationId } }); if (!before) throw new NotFoundError("Assignment not found"); const item = await prisma.stationAssignment.update({ where: { id: assignmentId }, data: { ...input, ...(input.active === false ? { effectiveTo: input.effectiveTo ?? new Date() } : {}) } }); await audit(adminId, stationId, "UPDATE_STATION_ASSIGNMENT", "StationAssignment", assignmentId, before, item); return item; },
  deleteAssignment: async (stationId: string, assignmentId: string, adminId: string) => { await ensureStation(stationId); const before = await prisma.stationAssignment.findFirst({ where: { id: assignmentId, stationId } }); if (!before) throw new NotFoundError("Assignment not found"); await prisma.stationAssignment.delete({ where: { id: assignmentId } }); await audit(adminId, stationId, "REMOVE_STATION_STAFF", "StationAssignment", assignmentId, before); return { success: true }; },
  maintenance: async (stationId: string, query: any) => { await ensureStation(stationId); const where: any = { stationId }; if (query.status) where.status = query.status; if (query.type) where.type = query.type; if (query.search) where.OR = [{ title: { contains: query.search, mode: "insensitive" } }, { description: { contains: query.search, mode: "insensitive" } }]; const [items, total] = await Promise.all([prisma.stationMaintenanceEvent.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.stationMaintenanceEvent.count({ where })]); const userIds = [...new Set(items.flatMap((x) => [x.assignedStaffId, x.createdById]).filter(Boolean) as string[])]; const users = await prisma.user.findMany({ where: { id: { in: userIds } }, select: { id: true, fullName: true } }); return { items: items.map((x) => ({ ...x, assignedStaff: users.find((u) => u.id === x.assignedStaffId) ?? null, createdBy: users.find((u) => u.id === x.createdById) ?? null })), total, page: query.page, limit: query.limit }; },
  createMaintenance: async (stationId: string, input: any, adminId: string) => { await ensureStation(stationId); if (input.assignedStaffId) { const assignment = await prisma.stationAssignment.findFirst({ where: { stationId, userId: input.assignedStaffId, active: true } }); if (!assignment) throw new BadRequestError("Assigned staff must have an active assignment at this station"); } const item = await prisma.stationMaintenanceEvent.create({ data: { ...input, stationId, createdById: adminId, startTime: input.startTime ?? new Date() } }); await audit(adminId, stationId, input.type === "INCIDENT" ? "CREATE_STATION_INCIDENT" : "CREATE_STATION_MAINTENANCE", "StationMaintenanceEvent", item.id, undefined, item); return item; },
  updateMaintenance: async (stationId: string, maintenanceId: string, input: any, adminId: string) => { await ensureStation(stationId); const before = await prisma.stationMaintenanceEvent.findFirst({ where: { id: maintenanceId, stationId } }); if (!before) throw new NotFoundError("Maintenance record not found"); const data = { ...input, ...((input.status === "RESOLVED" || input.status === "CANCELLED") ? { actualCompletion: new Date() } : {}) }; if (input.status === "RESOLVED" && !input.resolution) throw new BadRequestError("Resolution is required when resolving a record"); const item = await prisma.stationMaintenanceEvent.update({ where: { id: maintenanceId }, data }); await audit(adminId, stationId, "UPDATE_STATION_MAINTENANCE", "StationMaintenanceEvent", maintenanceId, before, item); return item; },
  reports: async (stationId: string, query: any) => { await ensureStation(stationId); const to = query.to ?? new Date(); const from = query.from ?? new Date(to.getTime() - 30 * 86400000); const [bookings, slots, bays, batteries, incidents, swaps] = await Promise.all([prisma.booking.findMany({ where: { stationId, createdAt: { gte: from, lte: to }, ...(query.bookingStatus ? { status: query.bookingStatus } : {}) }, select: { status: true } }), prisma.replacementSlot.findMany({ where: { stationId, date: { gte: from, lte: to }, ...(query.bayId ? { bayId: query.bayId } : {}) } }), prisma.serviceBay.count({ where: { stationId } }), prisma.battery.groupBy({ by: ["operationalStatus"], where: { stationId }, _count: true }), prisma.stationMaintenanceEvent.count({ where: { stationId, createdAt: { gte: from, lte: to } } }), prisma.swapTransaction.findMany({ where: { stationId, createdAt: { gte: from, lte: to } }, select: { workflowStatus: true, startedAt: true, completedAt: true, cost: true } })]); const completed = swaps.filter((x) => x.workflowStatus === "COMPLETED"); const durations = completed.filter((x) => x.completedAt).map((x) => x.completedAt!.getTime() - x.startedAt.getTime()); const totalCapacity = slots.reduce((sum, x) => sum + x.capacity, 0); const occupied = slots.reduce((sum, x) => sum + x.bookedCount + x.reservedCount, 0); const batteryCounts = Object.fromEntries(batteries.map((x) => [x.operationalStatus, x._count])); return { from, to, bookingVolume: bookings.length, slotUtilization: totalCapacity ? occupied / totalCapacity * 100 : 0, bayUtilization: bays ? slots.filter((x) => x.bookedCount > 0).length / Math.max(1, slots.length) * 100 : 0, completedReplacements: completed.length, replacementSuccessRate: swaps.length ? completed.length / swaps.length * 100 : 0, averageReplacementDurationMinutes: durations.length ? durations.reduce((a, b) => a + b, 0) / durations.length / 60000 : 0, batteryAvailability: batteryCounts.AVAILABLE ?? 0, lowInventoryCount: (batteryCounts.AVAILABLE ?? 0) < bays ? 1 : 0, maintenanceIncidents: incidents, bookingCancellationRate: bookings.length ? bookings.filter((x) => x.status === "CANCELLED").length / bookings.length * 100 : 0, bookingRejectionRate: bookings.length ? bookings.filter((x) => x.status === "REJECTED").length / bookings.length * 100 : 0, revenueTotal: completed.reduce((sum, x) => sum + x.cost, 0) }; },
  auditLogs: async (stationId: string, query: any) => { await ensureStation(stationId); const where = { stationId }; const [items, total] = await Promise.all([prisma.auditLog.findMany({ where, include: { admin: { select: { id: true, fullName: true, email: true, role: { select: { name: true } } } } }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.auditLog.count({ where })]); return { items, total, page: query.page, limit: query.limit }; },
};
